<?php
/**
 * type: page
 * title: Project release listing
 * description: Front page for listing recently submitted projects and their releases
 * version: 0.3
 * license: AGPL
 *
 * Frontpage.
 * Just shows the most recent projects and their released versions.
 *
 * Shows:
 *   → Recent projects and their released versions.
 *   → Visually trimmed descriptions and changelogs.
 *   → Small boxed tags.
 * Sidebar:
 *   → Newsfeeds (e.g. linux.com, /r/linux)
 * HTML:
 *   → RSS/Atom links for update feed comprised of all projects.
 *
 */


$header_add = "<link rel=alternate type=application/rss+xml href=/feed/xfer.rss>\n<link rel=alternate type=application/atom+xml href=/feed/xfer.atom>";
include("template/header.php");
include("template/sidebar_index.php");
?> <section id=main> <?php


// query projects
$page_no = $_GET->int->range…1…100["n"];
$releases = db("
    SELECT *
      FROM release_versions
     WHERE flag < 5
     LIMIT 40
    OFFSET 40*?
", $page_no - 1);


// show
foreach ($releases as $entry) {

    // HTML escaping and some autogenerated fields
    prepare_output($entry);
    // Callback for varexpression function calls in heredoc
    $_ = "trim";
    
    // Output
    print <<<HTML
      <article class=project>
        <h3>
            <a href="projects/$entry[name]">$entry[title]
            <em class=version>$entry[version]</em></a>
            <span class=links>
                <span class=published_date>$entry[formatted_date]</span>
                <a href="$entry[homepage]"><img src="img/home.png" width=20 height=20 border=0 align=middle></a>
                <a href="$entry[download]"><img src="img/disk.png" width=20 height=20 border=0 align=middle></a>
            </span>
        </h3>
        <a href="$entry[homepage]"><img class=preview src="$entry[image]" align=right width=120 height=90 border=0></a>
        <p class="description trimmed">$entry[description]</p>
        <p class="release-notes trimmed"><b>$entry[scope]:</b> $entry[changes]</p>
        <p class=tags><img src="img/tag.png" width=30 align=middle height=22 border=0><a class=license>$entry[license]</a>{$_(wrap_tags($entry["tags"]))}</p>
      </article>
HTML;

}


// add pseudo pagination (do not actually count available entries)
print "<p class=pagination-links> »";
foreach (range($page_no-2, $page_no+9) as $n) if ($n > 0) {
    print " <a " . ($n==$page_no ? "class=current " : ""). "href=\"?n=$n\">$n</a> ";
}
print "« </p>";


include("template/bottom.php");





?>